on:
    release:
    workflow_dispatch:
jobs:
    release:
        runs-on: ubuntu-latest
        permissions: write-all
        steps:
        -   uses: actions/checkout@v2
        -   uses: actions-rs/toolchain@v1
            with:
                toolchain: stable
                target: wasm32-unknown-unknown
        -   uses: actions-rs/cargo@v1
            with:
                command: build
                args: --target wasm32-unknown-unknown --release
        -   uses: softprops/action-gh-release@v2
            with: 
                files: target/wasm32-unknown-unknown/debug/orgora.wasm