on:
    release
jobs:
    release:
        runs-on: ubuntu-latest
        permissions: write-all
        steps:
        -   uses: actions/checkout@v2
        -   name: Compile and release
            uses: rust-build/rust-build.action@v1.4.5
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
                RUSTTARGET: "wasm32-wasi"
                EXTRA_FILES: "target/wasm32-wasi/debug/orgora.wasm"
          